### ISSUE TITLE
VasiliAutonomous and VasiliWaypointTrajectory

### ISSUE THREAD

**Issue by truher** [Team100/all24#11]
https://github.com/Team100/all24/blob/6ede966f9d2565a7b21ff4b922a2693a2040d929/comp/swerve100/src/main/java/org/team100/frc2023/autonomous/VasiliAutonomous.java#L23

do we use VasiliAutonomous and/or VasiliWaypointTrajectory?  what are they for?

**Comment by Coolearthsky** [comment]
Not really anything, I believe it was created in the past to test some auton but no idea why it even still exists.

**Comment by truher** [comment]
ok i'll delete it.
